name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/* # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the API
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Check code coverage
        run: npm run coverage

      - name: Check code coverage threshold (<90%)
        run: npx nyc check-coverage --lines 90 --functions 90 --branches 90
  uat:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/* # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the API
        run: npm run build

      - name: Install dependencies # Install dependencies
        run: npm ci

      - name: Deploy to UAT
        run: echo "Deploying to UAT environment... (We should be running npm run deploy:uat in actual deployment)"

      - name: Run Playwright E2E tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4 # Upload test results as an artifact
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/ # Upload the test results to the playwright-report directory
          retention-days: 30 # Set the retention days to 30 days
  production:
    runs-on: ubuntu-latest
    needs: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual approval
        run: echo "Please approve the deployment to production."

      - name: Deploy to Production
        run: echo "Deploying to PROD environment... (We should be running npm run deploy:prod in actual deployment)"
